import type { NextPage } from "next";
import Head from "next/head";
import RankingsContainer from "../components/RankingsContainer";
import Settings from "../components/Settings";
import { DataList } from "../data/Context";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>⚡ Power Rankings</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full w-full bg-[#2c2c2d]">
        <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
          <div className="mb-10 flex flex-col items-center">
            <h2 className="platchatText text-3xl font-light uppercase">
              Plat Chat Valorant
            </h2>
            <div className="relative my-2 w-[110%] flex-row justify-center">
              <div className="triangle absolute left-0 -translate-y-[45%]" />
              <div className="absolute top-0 h-[.1rem] w-full bg-white" />
              <div className="triangle absolute right-0 top-0 -translate-y-[45%] rotate-180" />
            </div>
            <h1 className="text-5xl font-bold uppercase text-white">
              Power Rankings
            </h1>
          </div>
          <DataList>
            <RankingsContainer />
          </DataList>
        </main>
        <div className="">
          <Settings />
        </div>
      </div>
    </>
  );
};

export default Home;
