import type { NextPage } from "next";
import Head from "next/head";
import Rankings from "../components/Rankings";
 
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>⚡ Power Rankings</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4 bg-[#2c2c2d]">
        <h2 className="uppercase font-light text-3xl platchatText">Plat Chat Valorant</h2>
        <h1 className="uppercase font-bold text-5xl text-white">Power Rankings</h1>
        <Rankings />
      </main>
    </>
  );
};

export default Home;
